server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/auth/ {
        proxy_pass http://auth-service:3001;
    }

    location /api/tasks/ {
        proxy_pass http://task-service:3002;
    }

    location /api/users/ {
        proxy_pass http://user-service:3003;
    }
}