events {}

http {

    server {
        listen 80;

        location / {
            proxy_pass http://frontend;
        }

        location /api/auth/ {
            proxy_pass http://auth-service:3001;
        }

        location /api/tasks/ {
            proxy_pass http://task-service:3002;
        }

        location /api/logs/ {
            proxy_pass http://log-service:3003;
        }
    }

}